--All valid elements in html5
--format: {tagName, void=isVoidElement, global=globalName}
--  void is used for void elements, which are not allowed to have
--  closing tags
--  global is used to give a custom name for an element. This is used
--  for table, because the element table clashes with the lua global

return {
	{'html', attributes={'manifest'}},
	{'head'},
	{'title'},
	{'base',void=true, attributes={'href', 'target'}},
	{'link',void=true, attributes={'href','crossorigin','red','media','hreflang','type','sizes'}},
	{'meta',void=true, attributes={'name','http-equiv','content','charset'}},
	{'style', attributes={'media','type'}},
	{'script', attributes={'src','type','charset','async','defer','crossorigin'}},
	{'noscript'},
	{'template'},
	{'body', attributes={'onafterprint','onbeforeprint','onbeforeunload','onhashchange','onmessage','onoffline','ononline','onpagehide','onpageshow','onpopstate','onstorage','onunload'}},
	{'section'},
	{'nav'},
	{'article'},
	{'aside'},
	{'h1'},
	{'h2'},
	{'h3'},
	{'h4'},
	{'h5'},
	{'h6'},
	{'header'},
	{'footer'},
	{'address'},
	{'main'},
	{'p'},
	{'hr',void=true},
	{'pre'},
	{'blockquote', attributes={'cite'}},
	{'ol', attributes={'reversed','start','type'}},
	{'ul'},
	{'li', attributes={'value'}},
	{'dl'},
	{'dt'},
	{'dd'},
	{'figure'},
	{'figcaption'},
	{'div'},
	{'a', attributes={'href','target','download','rel','hreflang','type'}},
	{'em'},
	{'strong'},
	{'small'},
	{'small'},
	{'s'},
	{'cite'},
	{'q', attributes={'cite'}},
	{'dfn'},
	{'abbr'},
	{'data', attributes={'value'}},
	{'time', attributes={'datetime'}},
	{'code'},
	{'var'},
	{'samp'},
	{'kbd'},
	{'sub'},
	{'sup'},
	{'i'},
	{'b'},
	{'u'},
	{'mark'},
	{'ruby'},
	{'rt'},
	{'rp'},
	{'bdi'},
	{'bdo'},
	{'span'},
	{'br',void=true},
	{'wbr',void=true},
	{'ins', attributes={'cite','datetime'}},
	{'del', attributes={'cite','datetime'}},
	{'img',void=true, attributes={'alt','src','crossorigin','usemap','ismap','width','height'}},
	{'iframe',attributes={'src','srcdoc','name','sandbox','width','height'}},
	{'embed',void=true, attributes={'src','type','width','height'}},
	{'object',attributes={'data','type','typemustmatch','name','usemap','form','width','height'}},
	{'param',void=true, attributes={'name','value'}},
	{'video', attributes={'src','crossorigin','poster','preload','autoplay','mediagroup','loop','muted','controls','width','height'}},
	{'audio',attributes={'src','crossorigin','preload','autoplay','mediagroup','loop','muted','controls'}},
	{'source',void=true, attributes={'src','type','media'}},
	{'track',void=true, attributes={'kind','src','srclang','label','default'}},
	{'canvas', attributes={'width','height'}},
	{'map', attributes={'name'}},
	{'area',void=true, attributes={'alt','coords','shape','href','target','download','rel','hreflang','type'}},
	{'svg'},
	{'math'},
	{'table',global='tab'},
	{'caption'},
	{'colgroup', attributes={'span'}},
	{'col',void=true, attributes={'span'}},
	{'tbody'},
	{'thead'},
	{'tfoot'},
	{'tr'},
	{'td', attributes={'colspan','rowspan','headers'}},
	{'th', attributes={'colspan','rowspan','headers','scope','abbr'}},
	{'form', attributes={'accept-charset','autocomplete','action','enctype','method','name','novalidate','target'}},
	{'fieldset', attributes={'disabled','form','name'}},
	{'legend'},
	{'label', attributes={'for','form'}},
	{'input',void=true, attributes={
		"accept",
		"alt",
		"autocomplete",
		"autofocus",
		"checked",
		"dirname",
		"disabled",
		"form",
		"formaction",
		"formenctype",
		"formmethod",
		"formnovalidate",
		"formtarget",
		"height",
		"list",
		"max",
		"maxlength",
		"min",
		"minlength",
		"multiple",
		"name",
		"pattern",
		"placeholder",
		"readonly",
		"required",
		"size",
		"src",
		"step",
		"type",
		"value",
		"width",
	}},
	{'button', attributes={'autofocus','disabled','form','formaction','formenctype','formmethod','formnovalidate','formtarget','name','type','value',}},
	{'select', attributes={'autofocus','disabled','form','multiple','required','name','value',}},
	{'datalist'},
	{'optgroup', attributes={'disabled','label'}},
	{'option',attributes={'disabled','label','selected','value'}},
	{'textarea', attributes={"autocomplete","autofocus","cols","dirname","disabled","form","maxlength","minlength","name","placeholder","readonly","required","rows","wrap",}},
	{'keygen',void=true, attributes={'autofocus','challenge','disabled','form','keytype','name'}},
	{'output', attributes={'for','form','name'}},
	{'progress', attributes={'value','max'}},
	{'meter', attributes={'value','min','max','low','high','optimum'}},
	{'details'},
	{'summary'},
	{'menuitem'},
	{'menu'}
}